# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
import pandas as pd
import plotly.graph_objects as go

# Page configuration
st.set_page_config(
    page_title="Home Loan vs Rental Calculator",
    page_icon="🏠",
    layout="wide"
)

# Title and introduction
st.title("🏠 Home Loan vs Rental Cost Comparison")
st.markdown("""
Compare the true cost of buying a home versus renting over time. 
This calculator considers mortgage payments, opportunity costs, maintenance, and more.
""")

st.divider()

# Create two columns for inputs
col1, col2 = st.columns(2)

with col1:
    st.subheader("🏡 Home Purchase Details")
    
    home_price = st.number_input(
        "Home Price ($)",
        min_value=50000,
        max_value=5000000,
        value=400000,
        step=10000,
        help="Total purchase price of the home"
    )
    
    down_payment_pct = st.slider(
        "Down Payment (%)",
        min_value=0,
        max_value=50,
        value=20,
        help="Percentage of home price paid upfront"
    )
    
    interest_rate = st.number_input(
        "Annual Interest Rate (%)",
        min_value=0.0,
        max_value=15.0,
        value=6.5,
        step=0.1,
        help="Annual mortgage interest rate"
    )
    
    loan_term = st.selectbox(
        "Loan Term (years)",
        options=[15, 20, 30],
        index=2,
        help="Length of mortgage in years"
    )
    
    property_tax_annual = st.number_input(
        "Annual Property Tax ($)",
        min_value=0,
        max_value=50000,
        value=5000,
        step=500,
        help="Yearly property tax amount"
    )
    
    home_insurance_annual = st.number_input(
        "Annual Home Insurance ($)",
        min_value=0,
        max_value=10000,
        value=1200,
        step=100,
        help="Yearly home insurance premium"
    )
    
    hoa_monthly = st.number_input(
        "Monthly HOA Fees ($)",
        min_value=0,
        max_value=2000,
        value=0,
        step=50,
        help="Monthly homeowners association fees (if applicable)"
    )
    
    maintenance_pct = st.slider(
        "Annual Maintenance (% of home value)",
        min_value=0.0,
        max_value=3.0,
        value=1.0,
        step=0.1,
        help="Typical range is 1-2% of home value per year"
    )

with col2:
    st.subheader("🏢 Rental Details")
    
    monthly_rent = st.number_input(
        "Monthly Rent ($)",
        min_value=500,
        max_value=20000,
        value=2500,
        step=100,
        help="Current monthly rent payment"
    )
    
    rent_increase_annual = st.slider(
        "Expected Annual Rent Increase (%)",
        min_value=0.0,
        max_value=10.0,
        value=3.0,
        step=0.5,
        help="Average yearly increase in rent"
    )
    
    renters_insurance_annual = st.number_input(
        "Annual Renter's Insurance ($)",
        min_value=0,
        max_value=1000,
        value=200,
        step=50,
        help="Yearly renter's insurance premium"
    )
    
    st.subheader("📊 Analysis Parameters")
    
    analysis_years = st.slider(
        "Analysis Period (years)",
        min_value=1,
        max_value=30,
        value=10,
        help="How many years to compare"
    )
    
    home_appreciation = st.slider(
        "Expected Home Appreciation (%/year)",
        min_value=0.0,
        max_value=10.0,
        value=3.0,
        step=0.5,
        help="Historical average is around 3-4%"
    )
    
    investment_return = st.slider(
        "Alternative Investment Return (%/year)",
        min_value=0.0,
        max_value=15.0,
        value=7.0,
        step=0.5,
        help="Return if down payment invested instead (e.g., stock market average ~7-10%)"
    )

st.divider()

# Calculate button
if st.button("📊 Calculate Comparison", type="primary", use_container_width=True):
    
    # CALCULATIONS
    # Down payment
    down_payment = home_price * (down_payment_pct / 100)
    loan_amount = home_price - down_payment
    
    # Monthly mortgage payment (Principal + Interest)
    monthly_interest_rate = interest_rate / 100 / 12
    num_payments = loan_term * 12
    
    if monthly_interest_rate > 0:
        monthly_mortgage = loan_amount * (
            monthly_interest_rate * (1 + monthly_interest_rate)**num_payments
        ) / ((1 + monthly_interest_rate)**num_payments - 1)
    else:
        monthly_mortgage = loan_amount / num_payments
    
    # Monthly ownership costs
    monthly_property_tax = property_tax_annual / 12
    monthly_insurance = home_insurance_annual / 12
    monthly_maintenance = (home_price * (maintenance_pct / 100)) / 12
    
    total_monthly_ownership = (
        monthly_mortgage + 
        monthly_property_tax + 
        monthly_insurance + 
        hoa_monthly + 
        monthly_maintenance
    )
    
    # Monthly rental costs
    monthly_renters_insurance = renters_insurance_annual / 12
    total_monthly_rental = monthly_rent + monthly_renters_insurance
    
    # Display immediate comparison
    st.subheader("💰 Monthly Cost Comparison")
    
    metric_col1, metric_col2, metric_col3 = st.columns(3)
    
    with metric_col1:
        st.metric(
            "Monthly Ownership Cost",
            f"${total_monthly_ownership:,.2f}",
            help="Total monthly cost of owning"
        )
    
    with metric_col2:
        st.metric(
            "Monthly Rental Cost",
            f"${total_monthly_rental:,.2f}",
            help="Total monthly cost of renting"
        )
    
    with metric_col3:
        difference = total_monthly_ownership - total_monthly_rental
        st.metric(
            "Monthly Difference",
            f"${abs(difference):,.2f}",
            delta=f"{'Buying costs more' if difference > 0 else 'Renting costs more'}",
            help="How much more expensive per month"
        )
    
    # Cost breakdown
    st.subheader("📋 Cost Breakdown")
    
    breakdown_col1, breakdown_col2 = st.columns(2)
    
    with breakdown_col1:
        st.markdown("**Ownership Costs:**")
        st.write(f"- Mortgage Payment: ${monthly_mortgage:,.2f}")
        st.write(f"- Property Tax: ${monthly_property_tax:,.2f}")
        st.write(f"- Home Insurance: ${monthly_insurance:,.2f}")
        st.write(f"- HOA Fees: ${hoa_monthly:,.2f}")
        st.write(f"- Maintenance: ${monthly_maintenance:,.2f}")
        st.write(f"- **Down Payment: ${down_payment:,.2f}** (one-time)")
    
    with breakdown_col2:
        st.markdown("**Rental Costs:**")
        st.write(f"- Monthly Rent: ${monthly_rent:,.2f}")
        st.write(f"- Renter's Insurance: ${monthly_renters_insurance:,.2f}")
    
    st.divider()
    
    # Multi-year analysis
    st.subheader(f"📈 {analysis_years}-Year Cost Analysis")
    
    # Build data for each year
    years = []
    ownership_cumulative = []
    rental_cumulative = []
    home_equity = []
    opportunity_cost_investment = []
    
    current_home_value = home_price
    current_rent = monthly_rent
    cumulative_own = down_payment  # Start with down payment
    cumulative_rent = 0
    remaining_principal = loan_amount
    invested_amount = down_payment  # If you had invested the down payment instead
    
    for year in range(1, analysis_years + 1):
        # Ownership costs this year
        yearly_ownership = total_monthly_ownership * 12
        cumulative_own += yearly_ownership
        
        # Rental costs this year
        yearly_rental = (current_rent + monthly_renters_insurance) * 12
        cumulative_rent += yearly_rental
        
        # Home appreciation
        current_home_value *= (1 + home_appreciation / 100)
        
        # Calculate equity (simplified - actual amortization is more complex)
        # This is approximate equity buildup
        yearly_principal_payment = monthly_mortgage * 12 - (remaining_principal * interest_rate / 100)
        remaining_principal -= yearly_principal_payment
        equity = current_home_value - remaining_principal
        
        # Investment growth if down payment was invested
        invested_amount *= (1 + investment_return / 100)
        invested_amount += (total_monthly_ownership - total_monthly_rental) * 12  # Invest the difference each year
        
        # Store data
        years.append(year)
        ownership_cumulative.append(cumulative_own)
        rental_cumulative.append(cumulative_rent)
        home_equity.append(equity)
        opportunity_cost_investment.append(invested_amount)
        
        # Increase rent for next year
        current_rent *= (1 + rent_increase_annual / 100)
    
    # Create comparison chart
    fig = go.Figure()
    
    fig.add_trace(go.Scatter(
        x=years,
        y=ownership_cumulative,
        name='Cumulative Ownership Costs',
        line=dict(color='#FF6B6B', width=3)
    ))
    
    fig.add_trace(go.Scatter(
        x=years,
        y=rental_cumulative,
        name='Cumulative Rental Costs',
        line=dict(color='#4ECDC4', width=3)
    ))
    
    fig.add_trace(go.Scatter(
        x=years,
        y=home_equity,
        name='Home Equity Built',
        line=dict(color='#95E1D3', width=2, dash='dash')
    ))
    
    fig.update_layout(
        title=f"Cost Comparison Over {analysis_years} Years",
        xaxis_title="Year",
        yaxis_title="Amount ($)",
        hovermode='x unified',
        height=500
    )
    
    st.plotly_chart(fig, use_container_width=True)
    
    # Final summary
    st.subheader("🎯 Summary")
    
    final_col1, final_col2 = st.columns(2)
    
    with final_col1:
        st.metric(
            f"Total Ownership Costs ({analysis_years} years)",
            f"${ownership_cumulative[-1]:,.2f}"
        )
        st.metric(
            f"Home Equity Built",
            f"${home_equity[-1]:,.2f}"
        )
        net_ownership = ownership_cumulative[-1] - home_equity[-1]
        st.metric(
            "Net Cost of Ownership",
            f"${net_ownership:,.2f}",
            help="Total costs minus equity built"
        )
    
    with final_col2:
        st.metric(
            f"Total Rental Costs ({analysis_years} years)",
            f"${rental_cumulative[-1]:,.2f}"
        )
        st.metric(
            "If Down Payment Was Invested",
            f"${opportunity_cost_investment[-1]:,.2f}",
            help="Value if you invested the down payment instead"
        )
        
    # Final verdict
    st.divider()
    
    if net_ownership < rental_cumulative[-1]:
        st.success(f"✅ **Buying is cheaper by ${rental_cumulative[-1] - net_ownership:,.2f}** over {analysis_years} years (after accounting for equity)")
    else:
        st.warning(f"⚠️ **Renting is cheaper by ${net_ownership - rental_cumulative[-1]:,.2f}** over {analysis_years} years")
    
    st.info("💡 **Remember:** This analysis doesn't account for tax benefits, closing costs, selling costs, or lifestyle factors. Consult with a financial advisor for personalized advice.")

else:
    st.info("👆 Fill in your details above and click 'Calculate Comparison' to see the results!")

# Footer
st.divider()
st.caption("Built with Streamlit | For educational purposes only")
